### ISSUE TITLE
IncompatibleClassChangeError: Found interface org.omnifaces.config.WebXml

### ISSUE THREAD

**Issue by rmpestano** [adminfaces/admin-template#123]
##### Issue Overview

Whenever an exception is thrown and not catched AdminFaces will redirect user to an error page. AdminFaces uses OmniFaces findErrorPageLocation utility to retrieve error pages from web.xml, [see here](https://github.com/adminfaces/admin-template/blob/b8cc2f2d98218ac13c7ce57f6e3ef725b569ae6e/src/main/java/com/github/adminfaces/template/exception/CustomExceptionHandler.java#L126). 

The error `IncompatibleClassChangeError`  happens when user upgrade their applications to OmniFaces 3.x where this method has changed and AdminFaces depends on a older version of OmniFaces (2.x).

Bellow is the stacktrace:
```
java.lang.IncompatibleClassChangeError: Found interface org.omnifaces.config.WebXml, but class was expected
	at com.github.adminfaces.template.exception.CustomExceptionHandler.findErrorPage(CustomExceptionHandler.java:126)
	at com.github.adminfaces.template.exception.CustomExceptionHandler.goToErrorPage(CustomExceptionHandler.java:105)
	at com.github.adminfaces.template.exception.CustomExceptionHandler.handleException(CustomExceptionHandler.java:75)
	at com.github.adminfaces.template.exception.CustomExceptionHandler.handle(CustomExceptionHandler.java:52)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:118)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:201)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:670)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1580)
```
##### Current Behaviour

AdminFaces can't redirect user to error pages when an uncaught exception is raised because of IncompatibleClassChangeError. 

##### Expected Behaviour

User should be redirected to error pages even when using OmniFaces 3.x.

##### How to reproduce  

Use OmniFaces 3.x on your application and throw and don't catch an exception.

 

##### Additional Information

* AdminFaces version:  RC18
* PrimeFaces version: 6.2
* JSF implementation:

**Comment by rmpestano** [comment]
Solution was to copy OmniFaces utility class to AdminFaces.
