### ISSUE TITLE
Add support for spring boot

### ISSUE THREAD

**Issue by maxsap** [adminfaces/admin-template#13]
I have tried running the project from a Spring boot application using JoinFaces and I am getting:

> java.lang.ExceptionInInitializerError: null
	at org.omnifaces.application.OmniApplication.<init>(OmniApplication.java:69) ~[omnifaces-2.1.jar:2.1]
	at org.omnifaces.application.OmniApplicationFactory.createOmniApplication(OmniApplicationFactory.java:89) ~[omnifaces-2.1.jar:2.1]
	at org.omnifaces.application.OmniApplicationFactory.getApplication(OmniApplicationFactory.java:54) ~[omnifaces-2.1.jar:2.1]
	at com.sun.faces.application.InjectionApplicationFactory.getApplication(InjectionApplicationFactory.java:93) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.config.InitFacesContext.getApplication(InitFacesContext.java:142) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.lifecycle.ClientWindowFactoryImpl.<init>(ClientWindowFactoryImpl.java:62) ~[javax.faces-2.2.14.jar:2.2.14]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_112]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_112]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_112]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_112]
	at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_112]
	at javax.faces.FactoryFinderInstance.getImplGivenPreviousImpl(FactoryFinderInstance.java:405) ~[javax.faces-2.2.14.jar:2.2.14]
	at javax.faces.FactoryFinderInstance.getImplementationInstance(FactoryFinderInstance.java:251) ~[javax.faces-2.2.14.jar:2.2.14]
	at javax.faces.FactoryFinderInstance.getFactory(FactoryFinderInstance.java:543) ~[javax.faces-2.2.14.jar:2.2.14]
	at javax.faces.FactoryFinder.getFactory(FactoryFinder.java:283) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.config.processor.FactoryConfigProcessor.verifyFactoriesExist(FactoryConfigProcessor.java:328) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.config.processor.FactoryConfigProcessor.process(FactoryConfigProcessor.java:236) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:439) ~[javax.faces-2.2.14.jar:2.2.14]
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:227) ~[javax.faces-2.2.14.jar:2.2.14]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4743) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_112]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_112]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_112]
Caused by: java.lang.IllegalStateException: CDI BeanManager instance is not available in JNDI.
	at org.omnifaces.config.BeanManager.<init>(BeanManager.java:99) ~[omnifaces-2.1.jar:2.1]
	at org.omnifaces.config.BeanManager.<clinit>(BeanManager.java:49) ~[omnifaces-2.1.jar:2.1]
	... 28 common frames omitted
Caused by: java.lang.IllegalStateException: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at org.omnifaces.util.JNDI.lookup(JNDI.java:92) ~[omnifaces-2.1.jar:2.1]
	at org.omnifaces.config.BeanManager.<init>(BeanManager.java:92) ~[omnifaces-2.1.jar:2.1]
	... 29 common frames omitted
Caused by: javax.naming.NoInitialContextException: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file:  java.naming.factory.initial
	at javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:662) ~[na:1.8.0_112]
	at javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:313) ~[na:1.8.0_112]
	at javax.naming.InitialContext.getURLOrDefaultInitCtx(InitialContext.java:350) ~[na:1.8.0_112]
	at javax.naming.InitialContext.lookup(InitialContext.java:417) ~[na:1.8.0_112]
	at org.omnifaces.util.JNDI.lookup(JNDI.java:88) ~[omnifaces-2.1.jar:2.1]
	... 30 common frames omitted

**Comment by rmpestano** [comment]
Hi @maxsap,

It it looks like an issue with OmniFaces dependency on CDI.  

Looking at [this thread](http://stackoverflow.com/questions/41416546/how-to-integrate-omnifaces-with-spring-boot) it suggests OmniFaces 1.x to work with SpringBoot as it is "CDIless". 

We could downgrade to OmniFaces 1.x in this project as well but there are other components that depend on CDI and may also break on a SpringBoot app. 

I'm not a Spring expert but I think that is more a SpringBoot CDI integration issue.

The components of AdminTemplate that depend on CDI are the following:

AdminSession
BreadCrumbMB
LogoutMB
AdminConfig
SkinMB

**Comment by maxsap** [comment]
Hello @rmpestano,

Thank you for the fast response, indeed I am already using JoinFaces and tried to use your awesome template.

In an attempt to test out the template, I excluded the omnifaces version coming from adminfaces and now I am getting:

`javax.faces.view.facelets.TagAttributeException: //Users/maxsap/Documents/workspace/wavy-admin/build/resources/main/META-INF/resources/index.xhtml @40,52 <ui:include src="/includes/top-bar.xhtml"> Invalid path : /includes/top-bar.xhtml
`
Which I am not 100% sure that its related to the CDI beans but more to where the resources are located.

After checking the beans that you specified it seems that most of them should be supported as spring should support `@NamedBeans`  natively but cannot handle `@SessionScoped`
Any chance we can work on a spring specific implementation? I am more than happy to help out.

**Comment by rmpestano** [comment]
Hi @maxsap,

for the include issue I think there should be a missing "top-bar.xhtml" in 'includes' folder. Both top-bar and includes are in the showcase application, not a admin-template thing.

About the SessionScoped handle I'm very open to add a spring boot compatible solution, have you already solved this issue? Maybe we could use Java Service loader to solve this, just wondering.

**Comment by rmpestano** [comment]
Hi @maxsap,

any news? do you have a sample project to share?

cheers!

**Comment by alissongodoi** [comment]
HI all,

   I added the following bean in my main Application Class and it kinds of solve the issue to load the Admin-Template.

	@Bean
	public AdminConfig adminConfig() {
		return new AdminConfig();
	}

   However I am still not able to get the template working. It looks like it renders the admin.xhtml as a template, however it does not find the source and images.

   Did you have any progress on this one?

**Comment by alissongodoi** [comment]
Guys, I did some progress with the following for Spring Boot:

1) For pom.xml:
- Installed the joinfaces in my project (version 2.4.0)
- Added admin-faces template to the project

2) For application.properties:
jsf.primefaces.theme=admin
jsf.primefaces.font-awesome=true

3) For SpringBootApplication.java starter, you need to tell SpringBoot to scan for the ServletComponents in the package:
@ComponentScan("com.github.adminfaces") -> This will scan for the Mbos in the Admin Faces lib.
@ServletComponentScan("com.github.adminfaces") -> This will start the filter and servlets.

4) Beans:
SpringBoot will complain that a Bean for the AdminSession has not been defined. Declare this in your application:
	@Bean
	public AdminSession adminSession() {
		return new AdminSession();
	}

If you want to configure the AdminConfig programatically like everything else in SpringBoot, you can also add the AdminConfig bean.
	@Bean
	public AdminConfig adminConfig() {
		return new AdminConfig();
	}

I didn't need to add the admin-faces.config file in the MEFA-INF, however you can also try it since I was able to verify that it loads properly once he ComponentScan is properly set.

I am still testing other aspects of this integration, however so far everything seems to work.

**Comment by rmpestano** [comment]
Hi @alissongodoi, that's great news!

If everything is ok, would you mind to send a pull request to [admin-boot](https://github.com/adminfaces/admin-boot)? 

Thank you very much for your help on this issue!

**Comment by alissongodoi** [comment]
hi @rmpestano - Brazuca também 👍 ,

     I have just got it working. Let me do more tests just to double check the best way to handle the Beans. Probably the AdminSession needs to be handled together with Spring Security. 

             Also, I am going to inject some real prime faces pages in the Template and let's see how it behaves. 

            Tomorrow I will try to check the admin-boot out and get the basics working, however I am not sure how to best externalise these configurations in the admin-boot for other people to reuse it.

     Probably we need to declare the AdminBootStarter and the users trying to use the lib would need to extend this Java class.

So far so good!

Cheers!

**Comment by rmpestano** [comment]
É nóis hehe

So my ideia with admin-boot is to create the same [admin-starter application](https://github.com/adminfaces) so you can put your customization like AdminConfig bean there in some package like "config".  We actually can rename it to "admin-starter-boot". 

Later we can think of providing a spring-boot starter (I'm not familiar with boot ecosystem) or something users can declare as dependency in their projects, what do you think?

**Comment by alissongodoi** [comment]
I found a bizarre error with Maven.

If Maven Repository is located in a directory with space (like windows 7 First name and Surname folder schema), the code fails to locate the /admin.xhtml template.

When I moved the Maven Repository to a folder without spaces (for example, c:\m2-repo), it worked properly. 

It was giving:

```
Invalid path : /admin.xhtml
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:179)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:312)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:371)
	at com.sun.faces.facelets.impl.DefaultFacelet.include(DefaultFacelet.java:350)
	at com.sun.faces.facelets.impl.DefaultFaceletContext.includeFacelet(DefaultFaceletContext.java:199)
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:174)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:93)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:87)
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:161)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:1006)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:99)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:659)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
```

**Comment by rmpestano** [comment]
Hi, that's really weird because template resolution is done at runtime (e.g when user access a page on browser) and maven resolves dependencies at build time. 

So the only thing that comes to mind is that using a folder with spaces on maven repo you were not downloading dependencies during build...

**Comment by CiceroRegis** [comment]
Hello good afternoon! I'm having the same probrema using JSF with maven. But I can not solve it yet.

**Comment by rmpestano** [comment]
Hi, have you looked into admin-starter-springboot project?

**Comment by CiceroRegis** [comment]
Actually I'm working on a project outside the template, and I would like to
add some components of this template only, but I'm not getting it because
an error occurs in the template jar

2018-08-03 16:18 GMT-03:00 Rafael M. Pestano <notifications@github.com>:

**Comment by rmpestano** [comment]
Which components? What's the error?

**Comment by CiceroRegis** [comment]
I'm trying to use the breadcrumb component, however the error that appears
is related to dependency
->Error:GRAVE: Exception starting filter
[com.github.adminfaces.template.session.AdminFilter]
java.lang.NullPointerException at
com.github.adminfaces.template.session.AdminFilter.init(AdminFilter.java:53)

2018-08-03 17:29 GMT-03:00 Rafael M. Pestano <notifications@github.com>:

**Comment by rmpestano** [comment]
> Actually I'm working on a project outside the template,

The breadcrumb component depends on admin-template, don't know how I could help if you can't use the template. You can look into the code and try to extract its logic from BreadCrumMB.

**Comment by CiceroRegis** [comment]
What kind of project?


Okay, I'll follow the logic, thank you.



2018-08-05 15:37 GMT-03:00 Rafael M. Pestano <notifications@github.com>:

**Comment by MahmoudOmarAbdelAzeem** [comment]
Hello
I get the below message any advice when using war instate of jar
java.lang.IllegalStateException: Unable to locate CDIProvider
