### ISSUE TITLE
NPE when using war deployment

### ISSUE THREAD

**Issue by Tosken1337** [adminfaces/admin-template#141]
Hi, i am using the joinfaces adminfaces-starter dependency for my project.
When running as spring boot jar with embedded tomcat everything works fine.

When using war deployment i am facing a NullPointerException in the AdminFilter because the AdminConfig could not be injected.

Any idea?

**Comment by rmpestano** [comment]
Hi, where are you using the war deployment? tomcat? 

I think you should open an issue on JoinFaces project and provide stacktrace, steps to reproduce and a sample project so they will be able to help you.

**Comment by Tosken1337** [comment]
Yes Tomcat.
The AdminFilter will be initialized by the servlet container due to the @WebFilter annotation and uses inject to wire some beans. But these beans cannot be wired because the AdminFilter is not instantiated by Spring i think.

**Comment by rmpestano** [comment]
So, it is JoinFaces that does this integration with Sprin, CDI and JSF. Not something we can fix in this project, I think.

**Comment by Tosken1337** [comment]
I created an issue
[https://github.com/joinfaces/joinfaces/issues/588](https://github.com/joinfaces/joinfaces/issues/588)

**Comment by persapiens** [comment]
Is it possible to configure `AdminFilter` and `LogoutServlet` at `web-fragment.xml` instead of using @WebFilter and @WebServlet annotations?

**Comment by rmpestano** [comment]
Sure, we can do that if it's causing problems in SpringBoot integration. Can you create a separated issue?

**Comment by persapiens** [comment]
> Sure, we can do that if it's causing problems in SpringBoot integration. Can you create a separated issue?

Anyway, it will not solve the problem. Tomcat will try to create `AdminFilter` and `LogoutServlet` when Tomcat is not embedded.
If you run Tomcat inside full java ee server, it will work because java ee server has DI capability. If you run embedded with spring boot, it work because spring has DI capability too. Single Tomcat does not have DI capability.

**Comment by rmpestano** [comment]
But in admin-starter-tomcat we add DI capability by adding CDI implementation and configuring BeanManager in [META-INF/context.xml](https://github.com/adminfaces/admin-starter-tomcat/blob/master/src/main/webapp/META-INF/context.xml) and weld in [web.xml](https://github.com/adminfaces/admin-starter-tomcat/blob/master/src/main/webapp/WEB-INF/web.xml#L40-L46), that doesn't help in this case also?

**Comment by rmpestano** [comment]
I see, It is more a springboot limitation than an AdminFaces issue. Can I close this issue or we can try something else

**Comment by persapiens** [comment]
> I see, It is more a springboot limitation than an AdminFaces issue. Can I close this issue or we can try something else?

Admin Template uses CDI injection in Servlet and Filter. Spring handle this only if it creates them. Unfortunately, this issue is not the case.

**Comment by DhannyaP** [comment]
HI, I am facing the same issue. Getting NPE on AdminFilter when running on Tomcat server. Could anyone help? 

java.lang.NullPointerException: null
	at com.github.adminfaces.template.session.AdminFilter.init(AdminFilter.java:53) ~[admin-template-1.0.0-RC20.jar:na]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:270) ~[catalina.jar:9.0.13]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:251) ~[catalina.jar:9.0.13]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:102) ~[catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4491) [catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5135) [catalina.jar:9.0.13]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.13]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1432) [catalina.jar:9.0.13]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1422) [catalina.jar:9.0.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.13]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_191]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:831) [catalina.jar:9.0.13]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.13]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1432) [catalina.jar:9.0.13]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1422) [catalina.jar:9.0.13]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_191]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) [tomcat-util.jar:9.0.13]
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) [na:1.8.0_191]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:944) [catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:261) [catalina.jar:9.0.13]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422) [catalina.jar:9.0.13]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.13]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:801) [catalina.jar:9.0.13]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:9.0.13]
	at org.apache.catalina.startup.Catalina.start(Catalina.java:695) [catalina.jar:9.0.13]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191]
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:350) [bootstrap.jar:9.0.13]
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:492) [bootstrap.jar:9.0.13]

**Comment by rmpestano** [comment]
Hi, have you tried with [admin-starter-tomcat](http://github.com/adminfaces/admin-starter-tomcat)?

**Comment by DhannyaP** [comment]
admin-starter-tomcat works, but it is not using spring boot.

My application is spring boot application with joinfaces and adminfaces.

**Comment by DhannyaP** [comment]
thanks it works fine when i give the bean manager in context.xml

**Comment by rmpestano** [comment]
That's is quite interesting! have you noticed any other side effect?

@persapiens anything else we should take into account? perhaps we should include context.xml in admin-starter-springboot aswell, WDYT?

**Comment by danjimgar** [comment]
> 
> 
> thanks it works fine when i give the bean manager in context.xml

Hello, 

Can you explain how did you do?

Thanks.

**Comment by rmpestano** [comment]
I think @DhannyaP did something like this: https://github.com/adminfaces/admin-template/issues/141#issuecomment-442879988

**Comment by danjimgar** [comment]
> I think @DhannyaP did something like this: [#141 (comment)](https://github.com/adminfaces/admin-template/issues/141#issuecomment-442879988)

Added the three things u told me, but giving the following error:

Caused by: java.lang.IllegalStateException: No WebApplicationContext found: no ContextLoaderListener registered?
	at org.springframework.web.jsf.FacesContextUtils.getRequiredWebApplicationContext(FacesContextUtils.java:83)
	at org.springframework.web.jsf.el.SpringBeanFacesELResolver.getWebApplicationContext(SpringBeanFacesELResolver.java:151)
	at org.springframework.web.jsf.el.SpringBeanFacesELResolver.getValue(SpringBeanFacesELResolver.java:78)
	at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:180)
	at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:208)
	at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:94)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:137)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at org.jboss.weld.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:115)
	at com.sun.faces.facelets.tag.TagAttributeImpl.getObject(TagAttributeImpl.java:358)
	at com.sun.faces.facelets.tag.TagAttributeImpl.getValue(TagAttributeImpl.java:324)
	at com.sun.faces.facelets.tag.ui.CompositionHandler.apply(CompositionHandler.java:167)
	at com.sun.faces.facelets.compiler.NamespaceHandler.apply(NamespaceHandler.java:94)
	at com.sun.faces.facelets.compiler.EncodingHandler.apply(EncodingHandler.java:88)
	at com.sun.faces.facelets.impl.DefaultFacelet.apply(DefaultFacelet.java:162)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.buildView(FaceletViewHandlingStrategy.java:381)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:102)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:223)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:671)
	... 26 more

**Comment by rmpestano** [comment]
Can you share your project?

**Comment by danjimgar** [comment]
> Can you share your project?

You can check it [here](https://github.com/danjimgar/primefacesLTE).

Thanks.

**Comment by danjimgar** [comment]
Hi @rmpestano did you check it?

Thanks.
