### ISSUE TITLE
Error deploying to Tomcat 8.5 on Windows Server

### ISSUE THREAD

**Issue by alaoa** [adminfaces/admin-template#157]
So when we deployed the application we got the following error starting up tomcat:

> SEVERE: Unable to process Jar entry [module-info.class] from Jar [file:/C:/Users/dev/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Admin/WEB-INF/lib/javax.json-api-1.1.3.jar] for annotations
> org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
>                 at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
>                 at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54)
>                 at org.apache.tomcat.util.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:174)
>                 at org.apache.tomcat.util.bcel.classfile.ClassParser.parse(ClassParser.java:83)

We removed the javax.json-api-1.1.3 reference and it went away but now we are getting this error

> 08-Feb-2019 13:08:08.883 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 1 Spring WebApplicationInitializers detected on classpath
> 08-Feb-2019 13:08:10.586 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.filterStart Exception starting filter com.github.adminfaces.template.session.AdminFilter
>  java.lang.NullPointerException
> 	at com.github.adminfaces.template.session.AdminFilter.init(AdminFilter.java:53)
> 	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279)
> 	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260)
> 	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105)
> 	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4572)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5215)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)

When looking at that line it seems the injection isn't working and the following attribute is null.

    @Inject
    AdminConfig adminConfig; 

* AdminFaces version:  admin-template-1.0.0-RC21
* PrimeFaces version: primefaces-6.2

**Comment by rmpestano** [comment]
Hi, do you see the same error when deploying [admin-starter-tomcat](https://github.com/adminfaces/admin-starter-tomcat)?

**Comment by alaoa** [comment]
I'm going to download that one and see if i get the same issue.

**Comment by alaoa** [comment]
After doing some research seems we have to move to TomEE.  We eventually want to go to a cloud environment but we are not ready at the moment.  I will close this as it has nothing to do with the showcase app and everything to do with Tomcat 8.5

**Comment by rmpestano** [comment]
Hi, I'm pretty sure It should run on Tomcat. I've test with Tomcat 8 and 9. Also made a vídeo of deploying on Tomcat 9: https://youtu.be/1h7yMYgCgdE
